import Navbar from '@/components/Navbar'
import './styles/global.scss'
import type { Metadata } from 'next'
import { Montserrat_Alternates } from 'next/font/google'
import Footer from '@/components/Footer'

const montserrat = Montserrat_Alternates({
    weight: ['400', '600'],
    subsets: ['latin'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={montserrat.className}>
                <header>
                    <Navbar />
                </header>
                <main className="flex-1 mx-auto w-full mb-10">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    )
}
